### PR TITLE
Load the sayings from the etherpad so that we get updates…

### PR DESCRIPTION
**Pull request by bwinton**
You didn't really want to keep the list in github anyways, did you?  ;)

### CODE REVIEW

**Comment by jeffgca** [comment]
Thanks!

**Comment by JohnMcLear** [comment]
Be mindful Mozilla is migrating their etherpad to the newer version that has a new export http endpoint.  Be mindful pro pads will be done AFTER public pads though so this might take some time :)

**Comment by bwinton** [comment]
This seems relevant to my interests.  Do you have any more information about it that I could read?  :)

**Comment by JohnMcLear** [comment]
```
 var url = 'https://firefox-ux.etherpad.mozilla.org/p/' + name + '/export/txt';
```

Will be the fix for when the new version is adopted, see moz bugtracker for migration progress also follow @rhelmer 's progress

**Comment by rhelmer** [comment]
Bug is https://bugzilla.mozilla.org/show_bug.cgi?id=831448

**Pull request merged**
